package cmn.catex.genomics.intervals;

import cmn.catex.cat.FiniteCategory;
import htsjdk.io.HtsPath;
import htsjdk.samtools.util.Interval;
import htsjdk.samtools.util.IntervalList;
import htsjdk.variant.vcf.VCFFileReader;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

import java.util.List;
import java.util.Map;

public class TestDataDiscoveryUtils {

    //*******************************************************************************************
    // disabled; used for finding suitable test data files
    @DataProvider(name = "featureFilesForOverlapQuery")
    public Object[][] getFeatureFilesForOverlapQuery() {
        return new Object[][] {
                { "../hellbender/./src/test/resources/large/Mills_and_1000G_gold_standard.indels.b37.sites.chr20.vcf" },
                { "../hellbender/./src/test/resources/large/sv/SvDiscoverFromLocalAssemblyContigAlignmentsSparkIntegrationTest_NonComplex.vcf" },
                { "../hellbender/./src/test/resources/large/sv/forBND_SvDiscoverFromLocalAssemblyContigAlignmentsSparkIntegrationTest_merged_simple.vcf" },
                { "../hellbender/./src/test/resources/large/sv/SvDiscoverFromLocalAssemblyContigAlignmentsSparkIntegrationTest_cpx_reinterpreted_simple_multi_seg.vcf" },
                { "../hellbender/./src/test/resources/large/sv/forBND_SvDiscoverFromLocalAssemblyContigAlignmentsSparkIntegrationTest_NonComplex.vcf" },
                { "../hellbender/./src/test/resources/large/sv/SvDiscoverFromLocalAssemblyContigAlignmentsSparkIntegrationTest_merged_simple.vcf" },
                { "../hellbender/./src/test/resources/large/sv/SvDiscoverFromLocalAssemblyContigAlignmentsSparkIntegrationTest_Complex.vcf" },
                { "../hellbender/./src/test/resources/large/sv/SvDiscoverFromLocalAssemblyContigAlignmentsSparkIntegrationTest_cpx_reinterpreted_simple_1_seg.vcf" },
                { "../hellbender/./src/test/resources/large/ReblockGVCF/spanDel.exome.chr20.vcf" },
                { "../hellbender/./src/test/resources/large/dbsnp_138.b37.20.21.vcf" },
                { "../hellbender/./src/test/resources/large/dbsnp_138.b37.1.1-65M.vcf" },
                { "../hellbender/./src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.tiny.vcf" },
                { "../hellbender/./src/test/resources/large/org/broadinstitute/hellbender/tools/walkers/vqsr/scalable/input/small_callset_low_threshold.sites-only.chr1.1-10M.vcf" },
                { "../hellbender/./src/test/resources/large/org/broadinstitute/hellbender/tools/walkers/vqsr/scalable/score/expected/extract.AS.snpIndel.posUn.train.snpIndel.posOnly.IF.score.snp.vcf" },
                { "../hellbender/./src/test/resources/large/org/broadinstitute/hellbender/tools/walkers/vqsr/scalable/score/expected/extract.nonAS.snpIndel.posUn.train.snpIndel.posOnly.IF.score.snpIndel.vcf" },
                { "../hellbender/./src/test/resources/large/org/broadinstitute/hellbender/tools/walkers/vqsr/scalable/score/expected/extract.AS.snpIndel.posUn.train.snpIndel.posOnly.IF.score.snpIndel.vcf" },
                { "../hellbender/./src/test/resources/large/org/broadinstitute/hellbender/tools/walkers/vqsr/scalable/score/expected/extract.nonAS.snpIndel.posUn.train.snpIndel.posOnly.IF.score.snp.vcf" },
                { "../hellbender/./src/test/resources/large/VQSR/bothRecal.vcf" },
                { "../hellbender/./src/test/resources/large/VQSR/combined.phase1.chr20.raw.indels.filtered.sites.1M-10M.vcf" },
                { "../hellbender/./src/test/resources/large/VQSR/expected/g94982_20_1m_10m_tranche_defaults.vcf" },
                { "../hellbender/./src/test/resources/large/VQSR/expected/g94982_20_1m_10m_tranched_99_99.5.vcf" },
                { "../hellbender/./src/test/resources/large/VQSR/expected/indelApplyResult.vcf" },
                { "../hellbender/./src/test/resources/large/VQSR/expected/g94982_20_1m_10m_tranched_99_with_old_filters.vcf" },
                { "../hellbender/./src/test/resources/large/VQSR/expected/g94982_20_1m_10m_tranched_95_99_99.9.vcf" },
                { "../hellbender/./src/test/resources/large/VQSR/ALL.wgs.indels_mills_devine_hg19_leftAligned_collapsed_double_hit.sites.20.1M-10M.vcf" },
                { "../hellbender/./src/test/resources/large/VQSR/g94982_b37_chr20_1m_10m.vcf" },
                { "../hellbender/./src/test/resources/large/VQSR/dbsnp_132_b37.leftAligned.20.1M-10M.vcf" },
                { "../hellbender/./src/test/resources/large/VQSR/indelRecal.vcf" },
                { "../hellbender/./src/test/resources/large/reblockGVCFs_AS_test.p_falciparum.g.vcf" },
                { "../hellbender/./src/test/resources/large/Ptrichocarpa.v3.sorted.p717.vcf" },
                { "../hellbender/./src/test/resources/large/Ptrichocarpa.v3.sorted.p717_2.vcf" },
                { "../hellbender/./src/test/resources/large/Ptrichocarpa.v3.p717.p717_2.combined.final.expected.vcf" },
                { "../hellbender/./src/test/resources/large/gvcfs/combined.gatk3.7_30_ga4f720357.expected.vcf" },
                { "../hellbender/./src/test/resources/large/gvcfs/gatk3.7_30_ga4f720357.24_sample.21.g.vcf" },
                { "../hellbender/./src/test/resources/large/gvcfs/CEUTrio.20.21.gatk3.4.g.vcf" },
                { "../hellbender/./src/test/resources/large/gvcfs/combined.gatk3.7.smaller_interval.g.vcf" },
                { "../hellbender/./src/test/resources/large/NA12878.HiSeq.WGS.b37_decoy.indel.recalibrated.chr20.vcf" },
                { "../hellbender/./src/test/resources/large/1000G.phase3.broad.withGenotypes.chr20.10100000.vcf" },
                { "../hellbender/./src/test/resources/large/expected.reblockGVCFs_AS_test.p_falciparum.rb.g.vcf" },
                { "../hellbender/./src/test/resources/large/funcotator/small_ds_pik3ca/dummy_clinvar_pik3ca/hg38/dummy_clinvar_hg38_pik3ca.vcf" },
                { "../hellbender/./src/test/resources/large/funcotator/ds_pik3ca_v43_WITH_MANE_SELECT_PLUS_CLINICAL_ANNOTATIONS_FOR_TEST/dummy_clinvar_pik3ca/hg38/dummy_clinvar_hg38_pik3ca.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/copynumber/gcnv-postprocess/segments_output_SAMPLE_001.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/copynumber/gcnv-postprocess/segments_output_SAMPLE_000.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/copynumber/gcnv-postprocess/segments_output_SAMPLE_002.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/VQSR/VQSR.mixedTest.recal.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/VQSR/VQSR.AStest.indels.recal.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/GenomicsDBImport/expected.testGVCFMode.gatk4.posteriors.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/GenomicsDBImport/expected.testGenomicsDBImportWithNonDiploidData.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/GenomicsDBImport/expected.testGVCFMode.gatk4.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/count_variants_withSequenceDict.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testPloidyRegions.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testGVCFMode.3.8-4-g7b0250253f.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testVCFMode.gatk4.withDDandDF.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testVCFMode.gatk4.nonstrict.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testGVCFMode.gatk4.posteriors.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testVCFMode.gatk3.8-4-g7b0250253f.alleleSpecific.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/testGenotypeGivenAllelesMode_givenAlleles.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testGVCFMode.gatk3.8-4-g7b0250253f.alleleSpecific.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testVCFMode.gatk3.8-4-g7b0250253.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testVCFMode.gatk4.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testLinkedDebruijnMode.gatk4.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testExposureOfSmithWatermanParameters.HC.gatk4.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testGVCFMode.gatk4.alleleSpecific.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.pileupCallerDRAGEN.378.gatk4.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testGVCFMode.gatk3.5.alleleSpecific.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testVCFMode.gatk4.DRAGEN.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testGVCFMode.gatk4.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/mutect/filtering/NA12878.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/mutect/expected.testExposureOfSmithWatermanParameters.M2.gatk4.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/mutect/cfdna/cfdna-unfiltered.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/mutect/dream/vcfs/sample_4.false_positives.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/mutect/dream/vcfs/sample_2.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/mutect/dream/vcfs/sample_3.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/testAlleleSpecificAnnotationsNoGroup.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/gvcfExample2WithTrailingReferenceBlocks.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/newMQcalc.combined.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/IntervalTest.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/twoSamples.MT.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/convertToBasePairResolution.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/testMultipleSpanningDeletionsForOneSampleHaploid.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/testMultipleSpanningDeletionsForOneSampleTetraploid.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/testBreakBandsArgumet.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/gvcfExample1.fullchrom.2021.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/gvcfWithTrailingReferenceBlocksExpected.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/spanningDeletionBaseExtensionTestExpected.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/testBasepairResolutionInput.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/gvcfExample1WithTrailingReferenceBlocks.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/testMultipleSpanningDeletionsForOneSample.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/spanningDeletionRestrictToStartExpected.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/testWrongReferenceBaseBugFix.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/twoSamples.MT.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/gvcfWithTrailingReferenceBlocksBandedExpected.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/testAlleleSpecificAnnotations.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/sample2.MT.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/YRIoffspring.chr20snippet.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/noGTCount.sample2.chr20snippet.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/NA12892.chrX.diploid.rb.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/noGTCount.expected.chr20snippet.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/fiveSampleTest.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/expected.hailOutput.chr20snippet.sites_only.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/sample1.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/sample2.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/NA12891.chrX.haploid.rb.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/haploidPlusDiploid.expected.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/sample4.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/sample5.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/hailOutput.chr20snippet.sites_only.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/noGTCount.sample1.chr20snippet.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/fiveSampleTest.lowerCallThreshold.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/LeftAlignAndTrimVariants/expected_left_align_hg38_split_multiallelics.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/LeftAlignAndTrimVariants/test_left_align_hg38.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/LeftAlignAndTrimVariants/expected_left_align_hg38_notrim.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/LeftAlignAndTrimVariants/expected_left_align_hg38_notrim_split_multiallelics.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/LeftAlignAndTrimVariants/expected_left_align_hg38.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/LeftAlignAndTrimVariants/expected_left_align_hg38_maxIndelSize296.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/LeftAlignAndTrimVariants/expected_left_align_hg38_split_multiallelics_keepOrigAC.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/LeftAlignAndTrimVariants/expected_left_align_hg38_maxIndelSize342.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/ReblockGVCF/overlappingDeletions.hc.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/ReblockGVCF/dropGQ0Dels.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/ReblockGVCF/noCallGTs.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/ReblockGVCF/reblockEdgeCase.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/ReblockGVCF/reblock_cleanup_bug_variant.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/ReblockGVCF/overlappingDels2.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/ReblockGVCF/regressionTests.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/hgdb_sv_multi_sample_mini.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/untrimmed.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/UpdateVCFSequenceDictionary/variantsWithDict.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/UpdateVCFSequenceDictionary/variantsWithSubsetDict.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/UpdateVCFSequenceDictionary/variantsWithDictBadContigLength.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenomicsDBImport/newMQcalc.combined.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/newMQcalc.combined.genotyped.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/multiSamples.expected.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/newMQcalc.combined.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/spanningDel.combined.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/multiSamples.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/leadingDeletion.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/CEUTrio.20.gatk3.7_30_ga4f720357.expected.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/expected/gvcf.basepairResolution.includeNonVariantSites.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/CEUTrio.21.gatk3.7_30_ga4f720357.expected.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/CEUTrio.20.21.gatk3.7_30_ga4f720357.expected.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/newMQcalc.singleSample.genotyped.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/ad-bug-input.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/twoReblocked.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/combined.single.sample.pipeline.gatk3.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/threeSamples.MT.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/expected.posteriors.genotyped.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/testAlleleSpecificAnnotations.CombineGVCF.output.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/CombineGVCFs.output.withoutIndex.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/CombineGVCFs.output.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/ValidateVariants/goodGVCF.inOrderThreeContigs.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/ValidateVariants/badGVCF.outOfOrderThreeContigs.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/ValidateVariants/hasRefBlockOverlaps.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/ValidateVariants/badGVCF.outOfOrder.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/ValidateVariants/badGVCF.outOfOrderTwoContigs.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/ValidateVariants/goodGVCF.inOrderTwoContigs.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/ValidateVariants/hasVariantOverlappingRefBlock.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/count_variants_withSequenceDict_noIndex.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/concordance/gatk4-dream3-x.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/concordance/gatk3-dream3-x.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/concordance/same-eval.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/concordance/same-truth.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/reference/CheckReferenceCompatibility/example_variants_withSequenceDict_withmd5.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/reference/CheckReferenceCompatibility/example_variants_withSequenceDict_withoutmd5s.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/validation/mc3/MC3.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/funcotator/validationTestData/regressionTestVariantSetHG38.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/funcotator/validationTestData/regressionTestVariantSet2_expected.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/funcotator/validationTestData/regressionTestVariantSetHG38_expected.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/funcotator/validationTestData/regressionTestVariantSet2.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/funcotator/validationTestData/regressionTestVariantSet1.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/funcotator/validationTestData/regressionTestHg19Large_expected.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/funcotator/validationTestData/regressionTestVariantSet1_expected.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/funcotator/triple_allele.vcf" },
                { "../hellbender/./src/test/resources/large/sv/SvDiscoverFromLocalAssemblyContigAlignmentsSparkIntegrationTest_NonComplex.vcf" },
                { "../hellbender/./src/test/resources/large/sv/forBND_SvDiscoverFromLocalAssemblyContigAlignmentsSparkIntegrationTest_merged_simple.vcf" },
                { "../hellbender/./src/test/resources/large/sv/SvDiscoverFromLocalAssemblyContigAlignmentsSparkIntegrationTest_cpx_reinterpreted_simple_multi_seg.vcf" },
                { "../hellbender/./src/test/resources/large/sv/forBND_SvDiscoverFromLocalAssemblyContigAlignmentsSparkIntegrationTest_NonComplex.vcf" },
                { "../hellbender/./src/test/resources/large/sv/SvDiscoverFromLocalAssemblyContigAlignmentsSparkIntegrationTest_merged_simple.vcf" },
                { "../hellbender/./src/test/resources/large/sv/SvDiscoverFromLocalAssemblyContigAlignmentsSparkIntegrationTest_Complex.vcf" },
                { "../hellbender/./src/test/resources/large/sv/SvDiscoverFromLocalAssemblyContigAlignmentsSparkIntegrationTest_cpx_reinterpreted_simple_1_seg.vcf" },
                { "../hellbender/./src/test/resources/large/ReblockGVCF/spanDel.exome.chr20.vcf" },
                { "../hellbender/./src/test/resources/large/dbsnp_138.b37.20.21.vcf" },
                { "../hellbender/./src/test/resources/large/dbsnp_138.b37.1.1-65M.vcf" },
                { "../hellbender/./src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.tiny.vcf" },
                { "../hellbender/./src/test/resources/large/org/broadinstitute/hellbender/tools/walkers/vqsr/scalable/input/small_callset_low_threshold.sites-only.chr1.1-10M.vcf" },
                { "../hellbender/./src/test/resources/large/org/broadinstitute/hellbender/tools/walkers/vqsr/scalable/score/expected/extract.AS.snpIndel.posUn.train.snpIndel.posOnly.IF.score.snp.vcf" },
                { "../hellbender/./src/test/resources/large/org/broadinstitute/hellbender/tools/walkers/vqsr/scalable/score/expected/extract.nonAS.snpIndel.posUn.train.snpIndel.posOnly.IF.score.snpIndel.vcf" },
                { "../hellbender/./src/test/resources/large/org/broadinstitute/hellbender/tools/walkers/vqsr/scalable/score/expected/extract.AS.snpIndel.posUn.train.snpIndel.posOnly.IF.score.snpIndel.vcf" },
                { "../hellbender/./src/test/resources/large/org/broadinstitute/hellbender/tools/walkers/vqsr/scalable/score/expected/extract.nonAS.snpIndel.posUn.train.snpIndel.posOnly.IF.score.snp.vcf" },
                { "../hellbender/./src/test/resources/large/VQSR/bothRecal.vcf" },
                { "../hellbender/./src/test/resources/large/VQSR/combined.phase1.chr20.raw.indels.filtered.sites.1M-10M.vcf" },
                { "../hellbender/./src/test/resources/large/VQSR/expected/g94982_20_1m_10m_tranche_defaults.vcf" },
                { "../hellbender/./src/test/resources/large/VQSR/expected/g94982_20_1m_10m_tranched_99_99.5.vcf" },
                { "../hellbender/./src/test/resources/large/VQSR/expected/indelApplyResult.vcf" },
                { "../hellbender/./src/test/resources/large/VQSR/expected/g94982_20_1m_10m_tranched_99_with_old_filters.vcf" },
                { "../hellbender/./src/test/resources/large/VQSR/expected/g94982_20_1m_10m_tranched_95_99_99.9.vcf" },
                { "../hellbender/./src/test/resources/large/VQSR/ALL.wgs.indels_mills_devine_hg19_leftAligned_collapsed_double_hit.sites.20.1M-10M.vcf" },
                { "../hellbender/./src/test/resources/large/VQSR/g94982_b37_chr20_1m_10m.vcf" },
                { "../hellbender/./src/test/resources/large/VQSR/dbsnp_132_b37.leftAligned.20.1M-10M.vcf" },
                { "../hellbender/./src/test/resources/large/VQSR/indelRecal.vcf" },
                { "../hellbender/./src/test/resources/large/reblockGVCFs_AS_test.p_falciparum.g.vcf" },
                { "../hellbender/./src/test/resources/large/Ptrichocarpa.v3.sorted.p717.vcf" },
                { "../hellbender/./src/test/resources/large/Ptrichocarpa.v3.sorted.p717_2.vcf" },
                { "../hellbender/./src/test/resources/large/Ptrichocarpa.v3.p717.p717_2.combined.final.expected.vcf" },
                { "../hellbender/./src/test/resources/large/gvcfs/combined.gatk3.7_30_ga4f720357.expected.vcf" },
                { "../hellbender/./src/test/resources/large/gvcfs/gatk3.7_30_ga4f720357.24_sample.21.g.vcf" },
                { "../hellbender/./src/test/resources/large/gvcfs/CEUTrio.20.21.gatk3.4.g.vcf" },
                { "../hellbender/./src/test/resources/large/gvcfs/combined.gatk3.7.smaller_interval.g.vcf" },
                { "../hellbender/./src/test/resources/large/NA12878.HiSeq.WGS.b37_decoy.indel.recalibrated.chr20.vcf" },
                { "../hellbender/./src/test/resources/large/1000G.phase3.broad.withGenotypes.chr20.10100000.vcf" },
                { "../hellbender/./src/test/resources/large/expected.reblockGVCFs_AS_test.p_falciparum.rb.g.vcf" },
                { "../hellbender/./src/test/resources/large/funcotator/small_ds_pik3ca/dummy_clinvar_pik3ca/hg38/dummy_clinvar_hg38_pik3ca.vcf" },
                { "../hellbender/./src/test/resources/large/funcotator/ds_pik3ca_v43_WITH_MANE_SELECT_PLUS_CLINICAL_ANNOTATIONS_FOR_TEST/dummy_clinvar_pik3ca/hg38/dummy_clinvar_hg38_pik3ca.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/copynumber/gcnv-postprocess/segments_output_SAMPLE_001.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/copynumber/gcnv-postprocess/segments_output_SAMPLE_000.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/copynumber/gcnv-postprocess/segments_output_SAMPLE_002.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/VQSR/VQSR.mixedTest.recal.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/VQSR/VQSR.AStest.indels.recal.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/GenomicsDBImport/expected.testGVCFMode.gatk4.posteriors.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/GenomicsDBImport/expected.testGenomicsDBImportWithNonDiploidData.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/GenomicsDBImport/expected.testGVCFMode.gatk4.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/count_variants_withSequenceDict.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testPloidyRegions.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testGVCFMode.3.8-4-g7b0250253f.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testVCFMode.gatk4.withDDandDF.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testVCFMode.gatk4.nonstrict.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testGVCFMode.gatk4.posteriors.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testVCFMode.gatk3.8-4-g7b0250253f.alleleSpecific.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/testGenotypeGivenAllelesMode_givenAlleles.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testGVCFMode.gatk3.8-4-g7b0250253f.alleleSpecific.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testVCFMode.gatk3.8-4-g7b0250253.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testVCFMode.gatk4.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testLinkedDebruijnMode.gatk4.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testExposureOfSmithWatermanParameters.HC.gatk4.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testGVCFMode.gatk4.alleleSpecific.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.pileupCallerDRAGEN.378.gatk4.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testGVCFMode.gatk3.5.alleleSpecific.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testVCFMode.gatk4.DRAGEN.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testGVCFMode.gatk4.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/mutect/filtering/NA12878.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/mutect/expected.testExposureOfSmithWatermanParameters.M2.gatk4.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/mutect/cfdna/cfdna-unfiltered.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/mutect/dream/vcfs/sample_4.false_positives.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/mutect/dream/vcfs/sample_2.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/mutect/dream/vcfs/sample_3.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/testAlleleSpecificAnnotationsNoGroup.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/gvcfExample2WithTrailingReferenceBlocks.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/newMQcalc.combined.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/IntervalTest.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/twoSamples.MT.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/convertToBasePairResolution.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/testMultipleSpanningDeletionsForOneSampleHaploid.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/testMultipleSpanningDeletionsForOneSampleTetraploid.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/testBreakBandsArgumet.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/gvcfExample1.fullchrom.2021.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/gvcfWithTrailingReferenceBlocksExpected.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/spanningDeletionBaseExtensionTestExpected.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/testBasepairResolutionInput.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/gvcfExample1WithTrailingReferenceBlocks.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/testMultipleSpanningDeletionsForOneSample.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/spanningDeletionRestrictToStartExpected.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/testWrongReferenceBaseBugFix.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/twoSamples.MT.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/gvcfWithTrailingReferenceBlocksBandedExpected.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/testAlleleSpecificAnnotations.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/sample2.MT.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/YRIoffspring.chr20snippet.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/noGTCount.sample2.chr20snippet.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/NA12892.chrX.diploid.rb.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/noGTCount.expected.chr20snippet.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/fiveSampleTest.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/expected.hailOutput.chr20snippet.sites_only.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/sample1.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/sample2.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/NA12891.chrX.haploid.rb.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/haploidPlusDiploid.expected.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/sample4.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/sample5.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/hailOutput.chr20snippet.sites_only.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/noGTCount.sample1.chr20snippet.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/fiveSampleTest.lowerCallThreshold.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/LeftAlignAndTrimVariants/expected_left_align_hg38_split_multiallelics.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/LeftAlignAndTrimVariants/test_left_align_hg38.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/LeftAlignAndTrimVariants/expected_left_align_hg38_notrim.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/LeftAlignAndTrimVariants/expected_left_align_hg38_notrim_split_multiallelics.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/LeftAlignAndTrimVariants/expected_left_align_hg38.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/LeftAlignAndTrimVariants/expected_left_align_hg38_maxIndelSize296.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/LeftAlignAndTrimVariants/expected_left_align_hg38_split_multiallelics_keepOrigAC.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/LeftAlignAndTrimVariants/expected_left_align_hg38_maxIndelSize342.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/ReblockGVCF/overlappingDeletions.hc.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/ReblockGVCF/dropGQ0Dels.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/ReblockGVCF/noCallGTs.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/ReblockGVCF/reblockEdgeCase.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/ReblockGVCF/reblock_cleanup_bug_variant.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/ReblockGVCF/overlappingDels2.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/ReblockGVCF/regressionTests.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/hgdb_sv_multi_sample_mini.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/untrimmed.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/UpdateVCFSequenceDictionary/variantsWithDict.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/UpdateVCFSequenceDictionary/variantsWithSubsetDict.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/UpdateVCFSequenceDictionary/variantsWithDictBadContigLength.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenomicsDBImport/newMQcalc.combined.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/newMQcalc.combined.genotyped.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/multiSamples.expected.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/newMQcalc.combined.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/spanningDel.combined.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/multiSamples.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/leadingDeletion.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/CEUTrio.20.gatk3.7_30_ga4f720357.expected.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/expected/gvcf.basepairResolution.includeNonVariantSites.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/CEUTrio.21.gatk3.7_30_ga4f720357.expected.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/CEUTrio.20.21.gatk3.7_30_ga4f720357.expected.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/newMQcalc.singleSample.genotyped.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/ad-bug-input.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/twoReblocked.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/combined.single.sample.pipeline.gatk3.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/threeSamples.MT.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/expected.posteriors.genotyped.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs/testAlleleSpecificAnnotations.CombineGVCF.output.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/CombineGVCFs.output.withoutIndex.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/CombineGVCFs.output.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/ValidateVariants/goodGVCF.inOrderThreeContigs.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/ValidateVariants/badGVCF.outOfOrderThreeContigs.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/ValidateVariants/hasRefBlockOverlaps.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/ValidateVariants/badGVCF.outOfOrder.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/ValidateVariants/badGVCF.outOfOrderTwoContigs.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/ValidateVariants/goodGVCF.inOrderTwoContigs.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/walkers/ValidateVariants/hasVariantOverlappingRefBlock.g.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/count_variants_withSequenceDict_noIndex.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/concordance/gatk4-dream3-x.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/concordance/gatk3-dream3-x.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/concordance/same-eval.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/concordance/same-truth.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/reference/CheckReferenceCompatibility/example_variants_withSequenceDict_withmd5.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/reference/CheckReferenceCompatibility/example_variants_withSequenceDict_withoutmd5s.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/validation/mc3/MC3.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/funcotator/validationTestData/regressionTestVariantSetHG38.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/funcotator/validationTestData/regressionTestVariantSet2_expected.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/funcotator/validationTestData/regressionTestVariantSetHG38_expected.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/funcotator/validationTestData/regressionTestVariantSet2.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/funcotator/validationTestData/regressionTestVariantSet1.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/funcotator/validationTestData/regressionTestHg19Large_expected.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/funcotator/validationTestData/regressionTestVariantSet1_expected.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/funcotator/triple_allele.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/funcotator/Three_sample_somatic.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/spark/sv/integration/outputs/cpx_reinterpreted_simple_multi_seg.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/tools/spark/sv/integration/inputs/CpxVariantReInterpreterSparkIntegrationTest_complex.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/engine/feature_data_source_test_withSequenceDict.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/engine/example_variants_withSequenceDict.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/engine/MultiVariantWalkerGroupedOnStart/gvcfExample2.copy.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/engine/MultiVariantWalkerGroupedOnStart/gvcfExample2.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/engine/MultiVariantDataSource/baseVariants.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/engine/MultiVariantDataSource/interleavedVariants_2_WithOverlap.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/engine/MultiVariantDataSource/baseVariantsConflictingDictionary.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/engine/MultiVariantDataSource/interleavedVariants_1.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/engine/MultiVariantDataSource/interleavedVariants_2.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/engine/MultiVariantDataSource/splitVariants_1.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/engine/MultiVariantDataSource/splitVariants_2.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/engine/MultiVariantDataSource/interleavedVariants_1_WithOverlap.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/engine/GCSTests/expected_VariantWalkerGCSSupportIntegrationTest_vcf_wholefile.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/engine/GCSTests/expected_VariantWalkerGCSSupportIntegrationTest_vcf_single_interval.vcf" },
                { "../hellbender/./src/test/resources/org/broadinstitute/hellbender/engine/GCSTests/expected_VariantWalkerGCSSupportIntegrationTest_vcf_multiple_intervals.vcf" },
        };
    }

    // find test files that have overlapping features
    @Test(dataProvider = "featureFilesForOverlapQuery", enabled = false)
    private void findFeatureFilesWithOverlaps(final String featureFilePath) {
        try (final VCFFileReader reader = new VCFFileReader(new HtsPath(featureFilePath).toPath(), false)) {
            final IntervalList intervalList = reader.toIntervalList();
            final FiniteCategory<IntervalList, Interval> finCat = GenomicIntervalTestUtils.toOverlapsCategory(intervalList);
            final Map<Interval, List<Interval>> morphisms = finCat.getMorphismMap();
            //print out each file that has overlapping features
            if (morphisms.entrySet().stream().anyMatch(entry -> entry.getValue().size() > 1)) {
                System.out.println("{ \"%s\" }".formatted(featureFilePath));
            }

            // print out each overlapping set
            morphisms.entrySet().forEach(entry -> {
                final List<Interval> overlaps = entry.getValue();
                if (overlaps.size() > 1) {
                    System.out.println("Overlapping intervals for key: " + entry.getKey());
                    overlaps.forEach(overlap -> System.out.println("   " + overlap));
                }
            });
        }
    }

}
